version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 30s
      timeout: 2s
      retries: 5
      start_period: 4s
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  init-postgres-data:
    image: postgres:15-alpine
    pull_policy: if_not_present
    depends_on:
      postgres:
        condition: service_healthy
    entrypoint: [ '/bin/sh', '-c' ]
    env_file:
      - .env
    volumes:
      - .:/workspace:cached
    command: |
      "
      cd /workspace/.devcontainer &&
      sh restore_sql_db.sh
      "

    deploy:
      resources:
        limits:
          memory: 200M

  redis:
    image: redis:7-alpine
    pull_policy: if_not_present
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 2s
      retries: 5
      start_period: 4s
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  frontend-review:
    build:
      context: ./.devcontainer
      dockerfile: Dockerfile
    pull_policy: if_not_present
    user: developer
    ports:
      - "4200:4200"
    entrypoint: []
    command: >
      /bin/bash -c "
      cd /FE && 
      npm install && 
      npm run build && 
      npm run start
      "
    env_file:
      - .env
    volumes:
      - ./FE:/FE:cached
    depends_on:
      - backend-review

  backend-review:
    build:
      context: ./.devcontainer
      dockerfile: Dockerfile
    pull_policy: if_not_present
    user: developer
    volumes:
      - ./BE:/BE:cached
    ports:
      - "3000:3000"
    entrypoint: []
    command: >
      /bin/bash -c "
      cd /BE && 
      npm install && 
      npm run build && 
      npm run start
      "
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data:
  redis_data:

